i18n.map('es', {
  accounts: 'Cuentas',
  edit_roles: 'Editar Roles',
  invalid_email: 'El email no es valido',
  passwords_must_match: 'Las contraseñas no son iguales',
  no_permission_for_roles: 'No tienes permisos para cambiar los roles de este usuario',
  invalid_invitation_code: 'El código de invitación es incorrecto',
  my_account: 'Mi Cuenta',
  name: 'Nombre',
  your_name: 'Tu Nombre',
  email: 'Email',
  roles: 'Roles',
  actions: 'Acciones',
  logout: 'Salir',
  update_profile: 'Editar Perfil',
  change_password: 'Cambiar Contraseña',
  invite: 'Invitar',
  invitation_created_successfully: 'Invitación creada correctamente',
  back: 'Atrás',
  invite_another: 'Invitar otro',
  select_new_user_roles: 'Selecciona los roles para el nuevo usuario',
  optional_new_user_email: 'Email del nuevo usuario (opcional)',
  cancel: 'Cancelar',
  login: 'Entrar',
  save: 'Guardar',
  register: 'Registrar',
  password_again: 'Contraseña (repetir)',
  select_user_roles: 'Selecciona los roles para este usuario',
  create_a: 'Crear un',
  create: 'Crear',
  no_permission: 'No hay permisos',
  delete: 'Borrar',
  are_you_sure_to_delete_this: 'Estas seguro que quieres borrar este',
  confirm: 'Confirmar',
  update: 'Editar',
  config: 'Configuración',
  dictionary: 'Diccionario',
  create_new_page: 'Crear una nueva página',
  choose_template: 'Elige un template',
  choose: 'Elegir',
  delete_page: 'Borrar página',
  are_you_sure_to_delete_this_page: 'Estás seguro de que quieres borrar esta página?',
  pages: 'Pagínas',
  update_page: 'Editar Página',
  app_configuration: 'Configuración',
  remove: 'Borrar',
  choose_file: 'Elegir archivo',
  file: 'Archivo',
  no_file: 'No hay un archivo seleccionado',
  file_id_not_found: 'El archivo de id {fileId} no fué encontrado',
  title: 'Titulo',
  item: 'item',
  items: 'items',
  users: 'usuarios',
  user: 'usuario',
  error_uploading_file: 'Error subiendo archivo',
  error_removing_file: 'Error borrando archivo'
})